"""add a phone number column to users table automatically

Revision ID: f6a841b0ed2c
Revises: dd63f288576f
Create Date: 2022-02-20 20:38:58.323655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a841b0ed2c'
down_revision = 'dd63f288576f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
